datadump:
  location:
    author: /Users/skminfotech/IdeaProjects/upgraded-pancake/myreads/src/main/resources/test-author.txt
    works: /Users/skminfotech/IdeaProjects/upgraded-pancake/myreads/src/main/resources/test-works.txt
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
  data:
    cassandra:
      keyspace-name: main
      username:
      password:
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connection-timeout: 10s
        init-query-timeout: 10s
datastax.astra:
  secure-connect-bundle: secure-connect-myreads.zip
astra.db:
  id:
  region: us-central1
  keyspace: myreads
  application.token:
