spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.b290fce65510dacb
            client-secret: 65d67b23f8ec715be860e4fb5f021530e54acc82
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connection-timeout: 10s
        init-query-timeout: 10s
datastax.astra:
  secure-connect-bundle: secure-connect-myreads.zip
astra.db:
  id: <astra-db-id>
  region: us-central1
  keyspace: myreads
  application.token: <token>
